In [34]:
import pandas as pd
import numpy as np

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [36]:
df = pd.read_csv('titanic.csv')

In [37]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

# Data cleaning

In [38]:
df.drop(columns=['zero','zero.1','zero.2','zero.3','zero.4','zero.5','zero.6','zero.7','zero.8','zero.9','zero.10','zero.11','zero.12','zero.13','zero.14','zero.15','zero.16','zero.17','zero.18'],inplace=True)

In [39]:
df

,Passengerid,Age,Fare,Sex,sibsp,Parch,Pclass,Embarked,2urvived
0,1,22.0,7.2500,0,1,0,3,2.0,0
1,2,38.0,71.2833,1,1,0,1,0.0,1
2,3,26.0,7.9250,1,0,0,3,2.0,1
3,4,35.0,53.1000,1,1,0,1,2.0,1
4,5,35.0,8.0500,0,0,0,3,2.0,0
...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,3,2.0,0
1305,1306,39.0,108.9000,1,0,0,1,0.0,0
1306,1307,38.5,7.2500,0,0,0,3,2.0,0
1307,1308,28.0,8.0500,0,0,0,3,2.0,0
1308,1309,28.0,22.3583,0,1,1,3,0.0,0

In [40]:
df.drop(columns=['Pclass'],inplace=True)

In [41]:
df

      Passengerid   Age      Fare  Sex  sibsp  Parch  Embarked  2urvived
0               1  22.0    7.2500    0      1      0       2.0         0
1               2  38.0   71.2833    1      1      0       0.0         1
2               3  26.0    7.9250    1      0      0       2.0         1
3               4  35.0   53.1000    1      1      0       2.0         1
4               5  35.0    8.0500    0      0      0       2.0         0
...           ...   ...       ...  ...    ...    ...       ...       ...
1304         1305  28.0    8.0500    0      0      0       2.0         0
1305         1306  39.0  108.9000    1      0      0       0.0         0
1306         1307  38.5    7.2500    0      0      0       2.0         0
1307         1308  28.0    8.0500    0      0      0       2.0         0
1308         1309  28.0   22.3583    0      1      1       0.0         0

[1309 rows x 8 columns]

In [42]:
# step 1 -> train/test/split
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(columns=['2urvived']),
                                                   df['2urvived'],
                                                   test_size=0.2,
                                                   random_state=42)

In [43]:
X_train.head()

     Passengerid   Age    Fare  Sex  sibsp  Parch  Embarked
772          773  57.0  10.500    1      0      0       2.0
543          544  32.0  26.000    0      1      0       2.0
289          290  22.0   7.750    1      0      0       1.0
10            11   4.0  16.700    1      1      1       2.0
147          148   9.0  34.375    1      2      2       2.0

In [44]:
Y_train.sample(6)

903     0
875     1
1236    0
749     0
1106    0
789     0
Name: 2urvived, dtype: int64

In [48]:
# imputation Transformer
trf1 = ColumnTransformer([
    ('impute_age', SimpleImputer(),[1]),
    ('imput_Embarked',SimpleImputer(strategy='most_frequent'),[6])  
],remainder='passthrough')

In [51]:
# one Hot encodeing 
trf2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output= False, handle_unknown='ignore'), [1, 6])
],remainder='passthrough')

In [55]:
#scaling 
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0, 10))
])

In [56]:
# Feacture Selection 
trf4 = SelectKBest(score_func=chi2, k = 5)

In [57]:
# train the model 
trf5 = DecisionTreeClassifier()

# Create Pipeline

In [58]:
Pipe = Pipeline([
    ('trf1', trf1), 
    ('trf2', trf2), 
    ('trf3', trf3), 
    ('trf4', trf4), 
    ('trf5', trf5)
])

In [60]:
# train 
Pipe.fit(X_train,Y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [1]),
                                                 ('imput_Embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=5,
                             score_func=<function chi2 at 0x000001CEEC5F18A0>)),
                ('trf5', DecisionTreeClassifier())])

# ML Model

In [67]:
# predict 
y_pred = Pipe.predict(X_test)

In [68]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [69]:
from sklearn.metrics import accuracy_score

In [70]:
accuracy_score(Y_test, y_pred)

0.7137404580152672

# Exporting Pipeline

In [71]:
import pickle

In [72]:
pickle.dump(Pipe, open('Pipe.pkl', 'wb'))